#公共配置
spring:
  profiles:
    active: dev
  application:
    name: server-turbine
    
server:
  port: 8700
  
turbine:
  appConfig: consumer-shop,consumer-admin #配置Eureka中的serviceId列表，表明监控哪些服务
  aggregator: 
    clusterConfig: default #指定聚合哪些集群，多个使用","分割，默认为default。
  clusterNameExpression: new String("default") #指定集群名称
      
#开发环境
---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://aurora:aurora@localhost:8000/eureka/
#生产环境
---
spring:
  profiles: pro
eureka:
  client:
    serviceUrl:
      defaultZone: http://aurora:aurora@ip:8000/eureka/
      